server:
  port: 8080
spring:
  application:
    name: owner-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://localhost:5434/ownerdb
    username: postgres
    password: postgres
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

pl:
  altkom:
    dkah:
      dog-service:
        url: http://localhost:8100
